# SmartOffers local runtime template
#
# Copy this file to smartoffers_runtime_local.ps1 for local use.
# The destination file is ignored by Git and must contain only local values.

$env:SMARTOFFERS_QA4_API_URL = "<SMARTOFFERS_QA4_API_URL>"
$env:SMARTOFFERS_QA4_ACM_CUSTOM_DB_DSN = "<SMARTOFFERS_QA4_ACM_CUSTOM_DB_DSN>"
$env:SMARTOFFERS_QA4_ACM_CUSTOM_DB_USER = "<SMARTOFFERS_QA4_ACM_CUSTOM_DB_USER>"
$env:SMARTOFFERS_QA4_ACM_CUSTOM_DB_PASSWORD = "<SMARTOFFERS_QA4_ACM_CUSTOM_DB_PASSWORD>"
$env:SMARTOFFERS_QA4_ACM_DB_DSN = "<SMARTOFFERS_QA4_ACM_DB_DSN>"
$env:SMARTOFFERS_QA4_ACM_DB_USER = "<SMARTOFFERS_QA4_ACM_DB_USER>"
$env:SMARTOFFERS_QA4_ACM_DB_PASSWORD = "<SMARTOFFERS_QA4_ACM_DB_PASSWORD>"
$env:SMARTOFFERS_QA4_ACM_SMOKE_SQL = "<SMARTOFFERS_QA4_ACM_SMOKE_SQL>"
$env:SMARTOFFERS_QA4_ACM_SMOKE_SQL_SHA256 = "<SMARTOFFERS_QA4_ACM_SMOKE_SQL_SHA256>"
$env:SMARTOFFERS_QA4_ACM_DESTINATION_FINGERPRINT = "<SMARTOFFERS_QA4_ACM_DESTINATION_FINGERPRINT>"
$env:SMARTOFFERS_QA4_BDA_DB_DSN = "<SMARTOFFERS_QA4_BDA_DB_DSN>"
$env:SMARTOFFERS_QA4_BDA_DB_USER = "<SMARTOFFERS_QA4_BDA_DB_USER>"
$env:SMARTOFFERS_QA4_BDA_DB_PASSWORD = "<SMARTOFFERS_QA4_BDA_DB_PASSWORD>"
$env:SMARTOFFERS_QA4_BDA_SMOKE_SQL = "<SMARTOFFERS_QA4_BDA_SMOKE_SQL>"
$env:SMARTOFFERS_QA4_BDA_SMOKE_SQL_SHA256 = "<SMARTOFFERS_QA4_BDA_SMOKE_SQL_SHA256>"
$env:SMARTOFFERS_QA4_BDA_DESTINATION_FINGERPRINT = "<SMARTOFFERS_QA4_BDA_DESTINATION_FINGERPRINT>"
$env:SMARTOFFERS_ORACLE_CLIENT_LIB_DIR = "<SMARTOFFERS_ORACLE_CLIENT_LIB_DIR>"

# Optional QA1 endpoint, if a future local flow explicitly needs it.
# $env:SMARTOFFERS_QA1_API_URL = "<SMARTOFFERS_QA1_API_URL>"
